version: "3.8"

services:
  go:
    image: advent-of-code:go
    build:
      context: .
      dockerfile: ./infra/Dockerfile.go

  rust:
    image: advent-of-code:rust
    build:
      context: .
      dockerfile: ./infra/Dockerfile.rust

  run:
    privileged: true
    image: advent-of-code:run
    build:
      context: .
      dockerfile: ./infra/Dockerfile.run
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./problems:/adventOfCode

  run-clean:
    privileged: true
    image: advent-of-code:run
    build:
      context: .
      dockerfile: ./infra/Dockerfile.run
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  dev:
    privileged: true
    image: advent-of-code:dev
    build:
      context: .
      dockerfile: ./infra/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/adventOfCode

  rust-dev:
    privileged: true
    image: advent-of-code:rust-dev
    build:
      context: .
      dockerfile: ./infra/Dockerfile.rust-dev
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/adventOfCode

